packages:
  - apps
  - packages/*
  - '!**/build'
  - '!**/dist'
  - '!**/coverage'

ignoredBuiltDependencies:
  - nx
  - sharp
  - workerd

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@sveltejs/kit'
  - '@swc/core'
  - esbuild
  - lmdb
  - msgpackr-extract
