name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get full git history for last modified dates
          submodules: recursive # Initialize and update git submodules
          token: ${{ secrets.GITHUB_TOKEN }} # Use token for submodule access

      - name: Initialize and update submodules to latest
        run: |
          git submodule init
          git submodule update --init --recursive --remote
          cd apps/contents
          git checkout master || git checkout main
          git pull origin master || git pull origin main
          cd ../..

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Setup Nx cache
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: ${{ runner.os }}-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-nx-

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Install tsx globally
        run: pnpm add -g tsx

      - name: Install Playwright in apps workspace
        run: cd apps && pnpm exec playwright install --with-deps chromium

      - name: Set GitHub token environment variable
        run: echo "GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Build with Nx
        run: pnpm build
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Cloudflare Pages
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy apps/build --project-name=helmyl-com --branch=${{ github.ref_name == 'master' && 'main' || github.head_ref || github.ref_name }}
          packageManager: pnpm
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
